/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    'intro',
    'getting-started',
    'configuration',
    {
      type: 'category',
      label: 'Module Guides',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'modules',
      },
      items: [
        'guides/users',
        'guides/keys',
        'guides/subusers',
        'guides/buckets',
        'guides/quota',
        'guides/ratelimit',
        'guides/usage',
        'guides/info',
      ],
    },
    {
      type: 'category',
      label: 'Platform Guides',
      collapsed: false,
      items: [
        'guides/rook-ceph',
        'guides/odf',
      ],
    },
    'guides/hooks',
    'compatibility',
    'error-handling',
    'recipes',
    {
      type: 'category',
      label: 'API Reference',
      link: {
        type: 'generated-index',
        title: 'API Reference',
        description: 'Auto-generated API documentation from TypeDoc.',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'api',
        },
      ],
    },
  ],
};

module.exports = sidebars;
