/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    'intro',
    'getting-started',
    'configuration',
    {
      type: 'category',
      label: 'Module Guides',
      link: {
        type: 'doc',
        id: 'modules',
      },
      items: ['guides/users'],
    },
    'error-handling',
    'recipes',
    {
      type: 'category',
      label: 'API Reference',
      link: {
        type: 'generated-index',
        title: 'API Reference',
        description: 'Auto-generated API documentation from TypeDoc.',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'api',
        },
      ],
    },
  ],
};

module.exports = sidebars;
